RAS-933 Auth SQL logs print email
ONSdigital/ras-rm-auth-service pull request #139
Opened 2024-01-08 09:46 UTC by arroyoAle

# What and why?

# How to test?

# Trello

2024-01-09 14:18 UTC, arroyoAle commented on ras_rm_auth_service/resources/tokens.py
> +        return make_response(jsonify({"title": AUTH_TOKEN_ERROR, "detail": e.__class__.__name__}), 500)
500 seems the most appropriate to me in this case

2024-01-10 08:45 UTC, SteveScorfield commented
/deploy scorfs

2024-01-10 09:13 UTC, SteveScorfield commented
/deploy scorfs

2024-01-10 09:33 UTC, SteveScorfield commented
/deploy scorfs

2024-01-10 09:53 UTC, SteveScorfield approved these changes
Tested and works as expected. Compared before and after code change messages and looks correct. Approved.

2024-01-10 16:01 UTC, LJBabbage requested changes
A couple of things to look at. There is at least one place that a re-raised SQLAlchemyError is not caught see batch_process_endpoints, there could be more, but I didn't check all 20 uses. Unless I have missed it I also didn't see a test for this

2024-01-11 15:15 UTC, arroyoAle commented on ras_rm_auth_service/db_session_handlers.py
>          logger.error(
Updated this to info logging

2024-01-11 15:16 UTC, arroyoAle commented on ras_rm_auth_service/db_session_handlers.py
> +            f"Rolling back database session due to {e.__class__.__name__}",
Reverted my changes and adding the action after the cause

2024-01-11 15:17 UTC, arroyoAle commented on ras_rm_auth_service/db_session_handlers.py
>              error_class=e.__class__.__name__,
Removed the e.class.name from the string, I'll leave the other one in so at lease we know what kind of SQL error is being raised

2024-01-11 15:19 UTC, arroyoAle commented on ras_rm_auth_service/db_session_handlers.py
>              connections_in_pool=current_app.db.engine.pool.checkedin(),
It was like this before, not sure it adds anything useful either and it has been around since 2018 - has been removed

2024-01-11 15:20 UTC, arroyoAle commented on ras_rm_auth_service/db_session_handlers.py
> +    except Exception as e:
It can't, has been removed

2024-01-11 15:20 UTC, arroyoAle commented on ras_rm_auth_service/db_session_handlers.py
> +        logger.error("Unknown error raised when committing to database", error_class=e.__class__.__name__)
Has been removed

2024-01-11 15:20 UTC, arroyoAle commented on ras_rm_auth_service/db_session_handlers.py
> +    except Exception as e:
Has been removed

2024-01-11 15:32 UTC, arroyoAle commented on ras_rm_auth_service/resources/tokens.py
> +        return make_response(jsonify({"title": AUTH_TOKEN_ERROR, "detail": e.__class__.__name__}), 500)
Yeah I agree, but this endpoint seems to need changes on top of this, for this error maybe a 503 would be appropriate?

2024-01-12 17:42 UTC, LJBabbage requested changes
All works and looks good, some minor stuff, I didn't mark everything as it was duplication, i.e tests names. I do think you are possibly mocking to low, we should have one test that exercises the decorator all the others can be at view level. I.e whatever calls the  methods that has the decorator on should be mocked to just return SQLAlchemyError

2024-01-12 17:42 UTC, LJBabbage commented on ras_rm_auth_service/db_session_handlers.py
> +        logger.info(
I can't find any use of non_transactional_session at all, so it can be deleted

2024-01-12 17:42 UTC, LJBabbage commented on ras_rm_auth_service/batch_process_endpoints.py
> +    except SQLAlchemyError as e:
A bit of duplication that could be rationalised, but nothing major

2024-01-12 17:42 UTC, LJBabbage commented on ras_rm_auth_service/resources/tokens.py
> +        return make_response(jsonify({"title": AUTH_TOKEN_ERROR, "detail": e.__class__.__name__}), 500)
Don't worry, 500 is fine, it was more a general moan and something that another story could/should be raised. Just not a fan of generic 500s

2024-01-12 17:42 UTC, LJBabbage commented on test/resources/test_tokens.py
> +        self.assertEqual(response.get_json(), {"detail": "SQLAlchemyError", "title": "Auth service tokens error"})
Didn't you put in constants in the file, you should use them in asserts if you did

2024-01-12 17:42 UTC, LJBabbage commented on test/resources/test_tokens.py
> +        """
You don't usually put in a doc string when using given, when, then. That's kind of the idea of them, if the title isn't enough you explain it as you step through the code

2024-01-12 17:42 UTC, LJBabbage commented on test/resources/test_account.py
> +    def test_get_user_database_disconnect(self, session_mock):
The code isn't causing a database_disconnect, it's just dealing with a SQLAlchemyError, the name should reflect that.

2024-01-12 17:42 UTC, LJBabbage commented on test/resources/test_tokens.py
> +    def test_post_tokens_with_database_disconnect(self, session_mock):
As above

2024-01-12 17:42 UTC, LJBabbage commented on test/resources/test_tokens.py
> +        response = self.client.post("/api/v1/tokens/", data=form_data, headers=self.headers)
Does it need all of this? just the error is fine. If you really want to keep this you should try to avoid reassign vars, it's technically fine here, but makes it hard to follow in the code

2024-01-12 17:42 UTC, LJBabbage commented on test/test_batch_process_endpoints.py
> +    def test_get_users_eligible_for_first_notification_with_database_disconnect(self, session_mock):
As above with name

2024-01-12 17:42 UTC, LJBabbage commented on test/test_batch_process_endpoints.py
> +        response = self.client.get("/api/batch/account/users/eligible-for-first-notification", headers=self.headers)
I haven't dug into the code, but can you get away without all of this, we just want to raise an error

2024-01-15 09:29 UTC, arroyoAle commented on test/resources/test_tokens.py
> +        self.assertEqual(response.get_json(), {"detail": "SQLAlchemyError", "title": "Auth service tokens error"})
Updated this

2024-01-15 09:29 UTC, arroyoAle commented on test/resources/test_tokens.py
> +        """
Removed the docstring

2024-01-15 09:29 UTC, arroyoAle commented on test/resources/test_account.py
> +    def test_get_user_database_disconnect(self, session_mock):
Updated name

2024-01-15 09:30 UTC, arroyoAle commented on test/resources/test_tokens.py
> +        response = self.client.post("/api/v1/tokens/", data=form_data, headers=self.headers)
Removed and still works

2024-01-15 09:30 UTC, arroyoAle commented on test/test_batch_process_endpoints.py
> +    def test_get_users_eligible_for_first_notification_with_database_disconnect(self, session_mock):
Updated name

2024-01-15 09:30 UTC, arroyoAle commented on test/test_batch_process_endpoints.py
> +        response = self.client.get("/api/batch/account/users/eligible-for-first-notification", headers=self.headers)
Removed and still works

2024-01-15 09:30 UTC, arroyoAle commented on ras_rm_auth_service/db_session_handlers.py
> +        logger.info(
Removed non_transactional_session

2024-01-15 09:32 UTC, arroyoAle commented on ras_rm_auth_service/batch_process_endpoints.py
> +    except SQLAlchemyError as e:
Not sure which bit you mean honestly

2024-01-15 14:33 UTC, LJBabbage commented on ras_rm_auth_service/batch_process_endpoints.py
> +    except SQLAlchemyError as e:
They all return 
```return make_response(jsonify({"title": BATCH_PROCESS_ERROR, "detail": e.__class__.__name__}), 500)```

2024-01-15 14:34 UTC, LJBabbage approved these changes

2024-01-15 14:49 UTC, merged