Gdpr user deletion
ONSdigital/ras-rm-auth-service pull request #56
Opened 2020-09-18 14:36 UTC by akssinhaamit

# Motivation and Context
The motivation of this PR is to provide functionality to delete user data for GDPR.

# What has changed
 * A new column has been added mark_for_deletion
 * existing delete endpoint has been modified for soft delete
 * A new endpoint has been provided for the scheduler to hard delete users marked for deletion.
 * Kubernetes corn job has been provided for hard delete

# How to test?
Smoke Test

# Links
[JIRA](https://collaborate2.ons.gov.uk/jira/browse/RAS-243)

2020-09-18 14:51 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-18 15:13 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-18 15:27 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-18 15:32 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-18 15:33 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-18 15:43 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-18 15:49 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-18 16:04 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-21 08:33 UTC, warrenbailey requested changes
One minor thing, but looks good 👍

2020-09-21 08:33 UTC, warrenbailey commented on ras_rm_auth_service/resources/account.py
> +            session.query(User).filter(User.mark_for_deletion == True).delete()
shouldn't this be ?

session.query(User).filter(User.mark_for_deletion is True).delete()

or even:
session.query(User).filter(User.mark_for_deletion).delete()

Or does SQLAlchemy require it to be like this?

2020-09-21 08:33 UTC, warrenbailey commented on Makefile
> +	pipenv run flake8 --max-line-length=120 --max-complexity=10 --extend-ignore=E712 .
Why are ignoring E712? 

If there's a good reason, then we should add a comment? or better still just add a ` # noqa` next to the code that needs skipping rather than doing it globally.

2020-09-21 09:03 UTC, akssinhaamit commented on ras_rm_auth_service/resources/account.py
> +            session.query(User).filter(User.mark_for_deletion == True).delete()
I thought `is True` should work but it seems it doesn't for SQLAlchemy. I tried it!

2020-09-21 09:04 UTC, akssinhaamit commented on Makefile
> +	pipenv run flake8 --max-line-length=120 --max-complexity=10 --extend-ignore=E712 .
`session.query(User).filter(User.mark_for_deletion == True).delete()` gives E712 error for linting and as ìs True`does not seems to work for SQL alcheme, had to provide this ignore.

2020-09-21 09:39 UTC, warrenbailey commented on Makefile
> +	pipenv run flake8 --max-line-length=120 --max-complexity=10 --extend-ignore=E712 .
could we do this instead then?

session.query(User).filter(User.mark_for_deletion == True).delete() # noqa

2020-09-21 09:40 UTC, warrenbailey commented on ras_rm_auth_service/resources/account.py
> +            session.query(User).filter(User.mark_for_deletion == True).delete()
I do remember something about SQLAlchemy needing this, w
eird as Python best practice is to avoid it.

2020-09-21 10:19 UTC, akssinhaamit commented on Makefile
> +	pipenv run flake8 --max-line-length=120 --max-complexity=10 --extend-ignore=E712 .
Sure!

2020-09-21 10:30 UTC, warrenbailey approved these changes

2020-09-21 10:34 UTC, merged