Due Deletion scheduler for account not accessed for a months.
ONSdigital/ras-rm-auth-service pull request #59
Opened 2020-09-28 15:57 UTC by akssinhaamit

# Motivation and Context
* create a scheduler to provide a due deletion notification to the users when their account has not be accessed for a duration.

# What has changed
* three additional scheduler job has been provided to carry out the tasks.
* code refactor has been done.
# How to test?
* we will have to create a test suite data to make sure all the scheduler provided carries out the tasks without any issues.

2020-09-29 10:04 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-29 13:33 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-29 15:21 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-29 15:59 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-29 16:09 UTC, akssinhaamit commented
/deploy sinhaa

2020-09-30 09:00 UTC, akssinhaamit commented
/deploy sinhaa

2020-10-01 09:57 UTC, akssinhaamit commented
/deploy sinhaa

2020-10-01 10:14 UTC, akssinhaamit commented
/deploy sinhaa

2020-10-01 11:04 UTC, akssinhaamit commented
/deploy sinhaa

2020-10-02 08:38 UTC, jterryons commented on _infra/docker/scheduler.Dockerfile
> +RUN apt-get update && apt-get install -y build-essential curl gunicorn
do we need gunicorn here?

2020-10-02 08:39 UTC, jterryons commented on _infra/helm/auth/Chart.yaml
> +appVersion: 2.0.20
Id increment minor here

2020-10-02 08:46 UTC, jterryons commented on ras_rm_auth_scheduler_service/scheduled_jobs/due_deletion_first_notification.py
> +def process_accounts_for_first_notification():
process_accounts_for_first_notification is identical to the second and third. refactor this.

2020-10-02 10:12 UTC, akssinhaamit commented on _infra/docker/scheduler.Dockerfile
> +RUN apt-get update && apt-get install -y build-essential curl gunicorn
gunicorn removed

2020-10-02 10:13 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/scheduled_jobs/due_deletion_first_notification.py
> +def process_accounts_for_first_notification():
👍

2020-10-02 10:40 UTC, warrenbailey requested changes

2020-10-02 10:40 UTC, warrenbailey commented on ras_rm_auth_scheduler_service/scheduled_jobs/helper.py
> +    if method_name == "warn":
Is self needed here? This method isn't attached to a class?

2020-10-02 10:40 UTC, warrenbailey commented on ras_rm_auth_scheduler_service/scheduled_jobs/helper.py
> +def add_severity_level(self, method_name, event_dict):
Is self needed here? This method isn't attached to a class?

2020-10-02 10:40 UTC, warrenbailey commented on ras_rm_auth_scheduler_service/helper.py
> +        # The stdlib has an alias
This seems a little strange, could we clarify the comment?

2020-10-02 10:40 UTC, warrenbailey commented on ras_rm_auth_scheduler_service/helper.py
> +def add_severity_level(self, method_name, event_dict):
is self needed as a param? It's not attached to a class?

2020-10-02 10:40 UTC, warrenbailey commented on ras_rm_auth_scheduler_service/notify_service.py
> +            self.publisher = pubsub_v1.PublisherClient()
could this be done in the _init_ method?

2020-10-02 10:40 UTC, warrenbailey commented on ras_rm_auth_scheduler_service/notify_service.py
> +            raise NotifyError('There was a problem sending a notification via pub-sub topic to GOV.UK Notify.'
should these exceptions be logged?

2020-10-02 12:29 UTC, akssinhaamit commented on _infra/helm/auth/Chart.yaml
> +appVersion: 2.0.20
👍

2020-10-02 12:33 UTC, akssinhaamit commented on _infra/helm/auth/templates/deployment.yaml
> +            value: "{{ .Values.notify.dueDeletionFirstNotificationTemplate }}"
Right!... taken out

2020-10-02 12:33 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/db/setup.py
> +def get_database():
👍

2020-10-02 12:34 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/db/setup.py
> +    except Exception:
👍

2020-10-02 12:34 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/scheduled_jobs/helper.py
> +    if method_name == "warn":
updated

2020-10-02 12:34 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/scheduled_jobs/helper.py
> +def add_severity_level(self, method_name, event_dict):
updated

2020-10-02 13:11 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/helper.py
> +        # The stdlib has an alias
addition comment added

2020-10-02 13:11 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/helper.py
> +def add_severity_level(self, method_name, event_dict):
updated

2020-10-02 13:13 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/notify_service.py
> +            self.publisher = pubsub_v1.PublisherClient()
:+1

2020-10-02 13:13 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/notify_service.py
> +            raise NotifyError('There was a problem sending a notification via pub-sub topic to GOV.UK Notify.'
added

2020-10-02 15:09 UTC, akssinhaamit commented
/deploy sinhaa

2020-10-05 10:35 UTC, warrenbailey requested changes

2020-10-05 10:35 UTC, warrenbailey commented on ras_rm_auth_scheduler_service/notify_service.py
> +            self.publisher = pubsub_v1.PublisherClient()
I see you changed this but then changed it back? Did it not work?

2020-10-05 10:35 UTC, warrenbailey commented on ras_rm_auth_scheduler_service/helper.py
> +           f"auth.user.account_creation_date between '{date_one}' AND '{date_two}' AND " \
This query feels complicated, I don't really understand why it's differentiating between account created and last login? and why the default value for account created is 2020-06-15. Perhaps we can have a quick discussion?

2020-10-05 10:35 UTC, warrenbailey commented on migrations/manual_scripts/add_notification_column.sql
> +    due_deletion_third_notification_date TIMESTAMP without time zone;
These column names might be better as:

first_notification
second_notification
third_notification

As it's the date they are sent rather then when they are due.

2020-10-05 12:11 UTC, akssinhaamit commented on _infra/helm/auth/templates/deployment.yaml
> -      {{- if .Values.database.sqlProxyEnabled }}
will revert it, as it was in that case to avoid blank volume

2020-10-05 12:11 UTC, akssinhaamit commented on _infra/helm/auth/values.yaml
> +sendEmailToGovNotify: true
Trying to keep all the features enabled for sandbox. currently all notification in sandbox works with test key

2020-10-05 12:12 UTC, akssinhaamit commented on _infra/helm/auth/values.yaml
> +  dueDeletionFirstNotificationTemplate: due_deletion_first_notification_templates
No sure, but trying to keep it consistent with all other services using notification templates.

2020-10-05 12:13 UTC, akssinhaamit commented on ras_rm_auth_scheduler_service/helper.py
> +           f"auth.user.account_creation_date between '{date_one}' AND '{date_two}' AND " \
As discussed, account created is the right column to add any date which has been introduced by us, rather the system.

2020-10-05 12:13 UTC, akssinhaamit commented on migrations/manual_scripts/add_notification_column.sql
> +    due_deletion_third_notification_date TIMESTAMP without time zone;
agree... will change it accordingly

2020-10-05 12:25 UTC, warrenbailey approved these changes

2020-10-05 12:38 UTC, merged