Removing sql proxy container from notification scheduler
ONSdigital/ras-rm-auth-service pull request #65
Opened 2020-11-05 14:53 UTC by akssinhaamit

# Motivation and Context

The sql proxy container for notification scheduler keeps running.

# What has changed
sql interaction from the scheduler has been removed and endpoints has been provided for the same.

# How to test?
Smoke test

# Links
[Trello](https://trello.com/c/cph1QMSk/170-s22-bug-auth-due-deletion-notification-scheduler-job-implementation-update)

2020-11-05 15:29 UTC, akssinhaamit commented
/deploy sinha

2020-11-05 15:33 UTC, akssinhaamit commented
/deploy sinhaa

2020-11-05 15:55 UTC, akssinhaamit commented
/deploy sinhaa

2020-11-09 14:12 UTC, mfcrocker approved these changes
LGTM but one stylistic comment

2020-11-09 14:12 UTC, mfcrocker commented on ras_rm_auth_service/batch_process_endpoints.py
> +    _datetime_24_months_ago = datetime.utcnow() - timedelta(days=730)
These should just be constants at the top rather than defining them for each method

2020-11-09 15:21 UTC, warrenbailey requested changes

2020-11-09 15:21 UTC, warrenbailey commented on ras_rm_auth_service/batch_process_endpoints.py
> +        return '', 200
rather than an empty string should this return an empty json object or a 404 response rather than a 200?

Otherwise I think the calling code may error if there are no users?

2020-11-09 15:21 UTC, warrenbailey commented on ras_rm_auth_service/batch_process_endpoints.py
> +        return '', 200
as above

2020-11-09 15:21 UTC, warrenbailey commented on ras_rm_auth_service/batch_process_endpoints.py
> +
as above

2020-11-09 15:21 UTC, warrenbailey commented on config.py
> +    AUTH_URL = os.getenv('AUTH_URL', 'http://localhost:8041')
I don't think we need a default value here in config, properly should follow the same approach as the PARTY url

2020-11-09 15:23 UTC, warrenbailey commented on ras_rm_auth_service/batch_process_endpoints.py
> +    _datetime_24_months_ago = datetime.utcnow() - timedelta(days=730)
though they are not static, the result will change each time the function is called as they call utcnow() at the point they are needed

2020-11-09 15:46 UTC, akssinhaamit commented on config.py
> +    AUTH_URL = os.getenv('AUTH_URL', 'http://localhost:8041')
Can't follow the same as PARTY url as the testing framework uses testing configuration while spinning up the flask application but the scheduler itself is not a flask application hence can't change it dynamically.

2020-11-09 15:47 UTC, akssinhaamit commented on ras_rm_auth_service/batch_process_endpoints.py
> +
👍

2020-11-09 15:47 UTC, akssinhaamit commented on ras_rm_auth_service/batch_process_endpoints.py
> +        return '', 200
👍

2020-11-09 15:47 UTC, akssinhaamit commented on ras_rm_auth_service/batch_process_endpoints.py
> +        return '', 200
👍

2020-11-09 15:59 UTC, warrenbailey approved these changes

2020-11-09 16:04 UTC, merged